apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: simple-k8s-server
  name: simple-k8s-server
spec:
  # use NodePort here to be able to access a port on each node
  type: NodePort
  ports:
  - port: 9090
  selector:
    io.kompose.service: simple-k8s-server

